"""Add contact table and update post schema

Revision ID: 481260cf0d09
Revises: e61590663ebc
Create Date: 2026-02-06 18:09:07.465409

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '481260cf0d09'
down_revision: Union[str, Sequence[str], None] = 'e61590663ebc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('posts', 'category',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('posts', 'author',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('posts', 'read_time',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('posts', 'published',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('posts', 'published',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('posts', 'read_time',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('posts', 'author',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('posts', 'category',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    # ### end Alembic commands ###
