"""fix: remove duplicate timestamps and create posts table

Revision ID: 55cc2608960b
Revises: fd7bdf166aea
Create Date: 2026-02-03 15:58:59.967884

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55cc2608960b'
down_revision: Union[str, Sequence[str], None] = 'fd7bdf166aea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
