"""Sync database structure

Revision ID: 936f5b8b65e3
Revises: 8628736567d4
Create Date: 2026-02-10 22:13:45.367432

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '936f5b8b65e3'
down_revision: Union[str, Sequence[str], None] = '8628736567d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('published_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'published_at')
    # ### end Alembic commands ###
